language: java
jdk:
- oraclejdk8
before_install:
- pip install --user codecov
after_success:
- codecov
before_cache:
- rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/
before_deploy:
- ./gradlew releaseZip
deploy:
  provider: releases
  api_key:
    secure: S0a3BsUrmCzssu+aPqKpkzqGvfCQDiSHevlYiW+jjLH/lOihYR6gPTEfiON4Xf0P/SMHuuAw2vCuC5Wc43wCME+rUeZ40nEhqTacFi4tulvEXATs4gZHX39wipih4TOqyG4EQSASILevAX2EZWTnVt0F9CuIQ8tJW0dNaw2LfBFuW/+KnlZQcyTrb72PLJng/FTHvx+cZl66EIr3QpZ7eWttUhDA7mvRhabOEl7UQwPqFErFmYvBRq6OydvbSrTne0ITFyYwNt0kz9mQtArhlEP8RbYmYX/Vh+1yW5dA7tU4ta5765Z3KGc9LeoEv60OKntmUbkqISOyb/TSqBvRzYWzLBDunBRA8ejbz0Xtoa8VnzhY/oU5fWaIINZ6Wiuq4aryfNgHPX1xIDIQehNmSe7CZxn5pd1jm/rHN3dE3C3iRdorOvdqnw+GSmvp30KqXXcnQlRHfZDihrI6sZ3ff92VlLsnVxjwXvtip2jKjeWupq3Uazz4s/RkyflvqIpvpoylwCxq1YX0F5NdUThyR0BHQvULjpwlnJZi6S/GynF+uEA6h+Wur2oUKDDjMEsjMxi3poBDuV9pTaXChrCC0d36/IlqDhbbUOrFXttq1fRApPN1lGQ+7OJ0gLa38tL5Vzm3PGhv58ldyBwdtIap4/d4wzgd84ooBY9LO7RMc0g=
  file_glob: true
  file: "./build/libs/JAlgoArena-Auth-*.zip"
  skip_cleanup: true
  on:
    repo: skorzeniak/JAlgoArena-Auth
    tags: true
